server:
  global:
    scrape_interval: 15s
  persistentVolume:
    enabled: true
    size: 8Gi
  
  serviceAccount:
    create: false
    name: prometheus-server

  service:
    type: ClusterIP

  extraScrapeConfigs: |
    - job_name: 'spring-boot'
      kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
              - default
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_label_app]
          action: keep
          regex: skilllink-app
        - source_labels: [__meta_kubernetes_pod_container_port_number]
          action: keep
          regex: 8080
        - source_labels: [__meta_kubernetes_namespace]
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: kubernetes_pod_name
      metrics_path: /actuator/prometheus

alertmanager:
  enabled: true
  persistentVolume:
    enabled: true
    size: 2Gi 